- name: Demo on another file
  hosts: all
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World
    - name: Include ANOTHER file
      ansible.builtin.include_tasks:
        file: another.yml

